{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fuzex.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fuzex.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "fuzex.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
{{- end }}
