#!/usr/bin/env python3
"""fuze-code-review verdict gate — the ONE decision that may fire `gh pr review --approve`.

WHY THIS EXISTS. `fuze-code-review.yml` asks an LLM (via fuze-code-action) to review a PR
diff and, when the review is genuinely clean, submit an APPROVING review so a bot-authored
PR can satisfy `required_approving_review_count: 1` + `require_last_push_approval: true`
without a human. An approval step that fires unconditionally is WORSE than no review gate at
all, because it LOOKS like a gate and is not — this fleet has spent weeks removing exactly
that shape (`|| true`, `continue-on-error`, a check that passes by not running). This script
is the single place that decides approve / request_changes / comment / abstain, so the
workflow itself never has to parse LLM output inline.

THE CONTRACT. The reviewer LLM is instructed to emit, after its prose, a JSON object between
two sentinel lines carrying a per-run NONCE:

    ===FUZE_REVIEW_VERDICT_JSON:<nonce>===
    {"verdict": "approve|request_changes|comment", "summary": "...", "findings": [...]}
    ===END_FUZE_REVIEW_VERDICT_JSON:<nonce>===

The nonce is generated by the WORKFLOW at run time, after the PR diff is already fixed, and
is never predictable from the diff content — so a PR whose diff contains a forged sentinel
block (prompt injection via a file that quotes this exact contract) cannot forge a match
without also guessing 128 bits of randomness drawn after that diff was written. The LAST
occurrence of the nonce-scoped block is used, which is a second, independent line of defense:
even a lucky nonce match earlier in the transcript (e.g. the model quoting the instructions
back) is expected to be superseded by the model's actual answer at the end.

FAIL-CLOSED RULES, encoded as data rather than left to the workflow's YAML `if:` conditions,
so they can be unit-tested directly and mutation-tested (flip any one of them and a test
must fail):

  1. fuze-code-action's own `conclusion` must be "success". Anything else (the provider
     chain was exhausted, errored, or never started) is an ABSTAIN — "no review was
     produced", never "clean".
  2. The sentinel block must be present exactly once for the given nonce, and must contain
     valid JSON with the exact required shape. Missing, duplicated-with-different-content,
     malformed, or schema-violating is an ABSTAIN. UNPARSEABLE IS NOT CLEAN.
  3. `verdict` must be one of the three known literal values. Anything else is an ABSTAIN.
  4. `verdict == "approve"` is only self-consistent when `findings` is an empty list. A
     model claiming "approve" while also listing findings is a contradiction, not a clean
     review — ABSTAIN (this also defends against a truncated / merged response where two
     answers got concatenated).
  5. A PR touching `.github/workflows/**`, `.github/actions/**`, `workflow-templates/**`,
     `governance/**`, `scripts/apply_ruleset.sh`, or `scripts/bootstrap/**` (the approval
     machinery and the org's governance surface) NEVER gets an automatic approval, no matter
     what the model said — downgraded to "comment" so a human is pulled in. This is a
     structural rule, checked against the actual changed-file list computed by the workflow
     from `git diff`, NOT against anything the model claims about its own diff — a
     self-approving change to the approval machinery must never be able to talk itself past
     this check.

  6. A `mode == "declined"` result on a PR that touches that same sensitive surface is the
     workflow-self-modification guard (claude-code-action refuses to review a PR that changes
     the workflow invoking it) — BY DESIGN, not a failure. It is DEFERRED to a non-approving,
     non-blocking "comment" (the review runs post-merge on the default branch) rather than
     abstained, so a legitimate workflow change is not permanently wedged against a gate that
     structurally cannot run on it. Guarded on BOTH the declined mode AND the sensitive-file
     change, never on `mode` alone: a decline without such a change still fails closed. A
     swallowed provider error does NOT reach this branch as a decline — classify.sh surfaces
     it as an availability failure — so a deferral can never mask a real fault.

Exit code is not the interface; call `decide()` from the workflow's own python step, or run
this file with the documented env vars to have it write GITHUB_OUTPUT directly (see `main`).
"""
from __future__ import annotations

import json
import os
import re
import secrets as _secrets_mod  # nonce generation; unrelated to GitHub Secrets
import sys

VALID_VERDICTS = ("approve", "request_changes", "comment")
DECISIONS = ("approve", "request_changes", "comment", "abstain")


def make_nonce() -> str:
    """A fresh, unpredictable-in-advance token for one review run's sentinel block."""
    return _secrets_mod.token_hex(16)


def _sentinel_pattern(nonce: str) -> re.Pattern:
    start = re.escape(f"===FUZE_REVIEW_VERDICT_JSON:{nonce}===")
    end = re.escape(f"===END_FUZE_REVIEW_VERDICT_JSON:{nonce}===")
    # DOTALL so the JSON body (which we do not expect to contain newlines, but must not
    # silently mis-parse if a model pretty-prints it) is captured in full. Non-greedy so a
    # transcript containing more than one nonce-scoped block still yields exactly the
    # separate blocks in order, rather than one span from the first start to the last end.
    return re.compile(f"{start}(.*?){end}", re.DOTALL)


def extract_verdict_json(result_text: str, nonce: str) -> tuple[dict | None, str]:
    """Find the LAST nonce-scoped sentinel block in `result_text` and parse it as JSON.

    Returns (parsed_dict_or_None, reason). `reason` is always populated (even on success,
    for logging) and is never assumed to contain secrets — it may itself echo back an
    attacker-controlled snippet, so callers must not treat it as trusted markup, only as a
    log line.
    """
    if not result_text:
        return None, "reviewer produced no output at all"
    if not nonce:
        return None, "internal error: no nonce was supplied to search for"

    matches = _sentinel_pattern(nonce).findall(result_text)
    if not matches:
        return None, "no verdict sentinel block found for this run's nonce"

    # LAST occurrence wins — see module docstring's second line of defense.
    raw = matches[-1].strip()
    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError as exc:
        return None, f"verdict block is not valid JSON: {exc}"

    if not isinstance(parsed, dict):
        return None, "verdict block did not decode to a JSON object"

    verdict = parsed.get("verdict")
    if verdict not in VALID_VERDICTS:
        return None, f"verdict field is not one of {VALID_VERDICTS!r}: {verdict!r}"

    findings = parsed.get("findings")
    if not isinstance(findings, list):
        return None, "findings field is missing or not a JSON array"
    for f in findings:
        if not isinstance(f, dict) or "description" not in f:
            return None, "a findings entry is not an object with a description"

    if verdict == "approve" and findings:
        return None, (
            "schema violation: verdict=approve but findings is non-empty — a clean "
            "verdict and reported findings are mutually exclusive"
        )

    summary = parsed.get("summary")
    if not isinstance(summary, str):
        summary = ""

    return {"verdict": verdict, "summary": summary, "findings": findings}, "ok"


def decide(action_conclusion: str, result_text: str, nonce: str,
           sensitive_files: list[str], mode: str = "") -> dict:
    """The single decision point. Returns a dict with keys: decision, reason, verdict,
    summary, findings, downgraded (bool: true iff a model "approve" was overridden by the
    sensitive-files rule), deferred (bool: true iff the review was legitimately deferred by
    the workflow-self-modification guard — see rule 6 below).

    `decision` is always one of DECISIONS. Only `decision == "approve"` may ever result in
    the workflow calling `gh pr review --approve` — every other value must not.
    """
    if action_conclusion != "success":
        # RULE 6 — WORKFLOW-SELF-MODIFICATION GUARD IS A DEFERRAL, NOT A FAILURE.
        # claude-code-action deliberately DECLINES to review a PR that modifies the workflow
        # file invoking it (every workflow-migration PR trips it); fuze-code-action reports
        # that as mode == "declined". Nothing ran and nothing is broken — the review runs
        # post-merge on the default branch — so turning the required check red there would
        # permanently wedge every legitimate workflow change against a gate that structurally
        # cannot run on it. Such a decline is DEFERRED (a non-approving, non-blocking
        # "comment") rather than abstained.
        #
        # Guarded on BOTH signals, never on `mode` alone: the decline must coincide with the
        # PR actually touching the sensitive CI/governance surface (the exact precondition for
        # the guard, computed by the workflow from `git diff`). A "declined" with no such
        # change is not the guard but an unexplained no-op, and still fails closed as an
        # abstain. A swallowed provider error no longer reaches here as a decline at all —
        # classify.sh surfaces it as an availability failure — so this branch cannot mask a
        # real auth/quota fault as a benign deferral.
        if mode == "declined" and sensitive_files:
            return {
                "decision": "comment",
                "reason": (
                    "review deferred by claude-code-action's workflow-self-modification "
                    "guard: this PR changes CI/governance files (" + ", ".join(sensitive_files)
                    + "), which the reviewer refuses to run against on-PR by design. The review "
                    "runs post-merge on the default branch. This is NOT a review failure and "
                    "does not block the check; the required gates and human review still apply."
                ),
                "verdict": None, "summary": "", "findings": [], "downgraded": False,
                "deferred": True,
            }
        return {
            "decision": "abstain",
            "reason": (
                f"fuze-code-action conclusion was {action_conclusion!r}, not 'success' — no "
                "review was produced, so none can be approved. See the per-rung "
                "'fuze-code-action' notices in the job log for the specific classification "
                "(availability / task / declined) and, on an availability failure, the named "
                "provider error that triggered it."
            ),
            "verdict": None, "summary": "", "findings": [], "downgraded": False,
            "deferred": False,
        }

    parsed, reason = extract_verdict_json(result_text, nonce)
    if parsed is None:
        return {
            "decision": "abstain",
            "reason": f"reviewer output was unusable: {reason}",
            "verdict": None, "summary": "", "findings": [], "downgraded": False,
        }

    verdict = parsed["verdict"]
    findings = parsed["findings"]
    summary = parsed["summary"]

    if verdict == "approve" and sensitive_files:
        return {
            "decision": "comment",
            "reason": (
                "the model's verdict was 'approve', but this PR touches CI/governance "
                "files (" + ", ".join(sensitive_files) + "). A self-approving change to "
                "the approval machinery deserves a human — auto-approve is disabled for "
                "this class of change regardless of review outcome."
            ),
            "verdict": verdict, "summary": summary, "findings": findings, "downgraded": True,
        }

    return {
        "decision": verdict,
        "reason": "ok",
        "verdict": verdict, "summary": summary, "findings": findings, "downgraded": False,
    }


def render_body(result: dict, mode: str, vendor: str) -> str:
    """Human-readable GitHub review body for the decision `result` from decide()."""
    lines = ["## fuze-code-review — automated verdict", ""]

    if result["decision"] == "abstain":
        lines.append("**No verdict was reached — this run is NOT an approval.**")
        lines.append("")
        lines.append(result["reason"])
        lines.append("")
        lines.append(
            "This is reported as a failed check deliberately: a review that could not "
            "run must never be silently indistinguishable from a clean one."
        )
        return "\n".join(lines)

    if result.get("deferred"):
        lines.append("**Review deferred — this is not a failure.**")
        lines.append("")
        lines.append(result["reason"])
        lines.append("")
        lines.append(
            "_Only the automated AI review is deferred; the required gates and human "
            "review still gate this PR. The review runs on the post-merge commit on the "
            "default branch, which no longer modifies the reviewer's own workflow._"
        )
        return "\n".join(lines)

    if result["downgraded"]:
        lines.append("**Human review required — auto-approve disabled for this PR.**")
        lines.append("")
        lines.append(result["reason"])
        lines.append("")

    summary = result.get("summary") or "(no summary provided)"
    lines.append(f"**Summary:** {summary}")
    lines.append("")

    findings = result.get("findings") or []
    if findings:
        lines.append("**Findings:**")
        for f in findings:
            path = f.get("path") or "(unspecified path)"
            line_no = f.get("line")
            loc = f"{path}:{line_no}" if line_no not in (None, "") else path
            lines.append(f"- `{loc}` — {f.get('description', '')}")
        lines.append("")

    decision_label = {
        "approve": "APPROVED — no blocking findings.",
        "request_changes": "CHANGES REQUESTED — see findings above.",
        "comment": "COMMENT ONLY — not an approval.",
    }[result["decision"]]
    lines.append(f"**Verdict:** {decision_label}")
    lines.append("")
    lines.append(f"_Served by fuze-code-action (mode={mode or 'unknown'}, vendor={vendor or 'unknown'})._")
    return "\n".join(lines)


def _write_github_output(decision: dict, body: str) -> None:
    out_path = os.environ.get("GITHUB_OUTPUT")
    if not out_path:
        print(json.dumps({"decision": decision["decision"], "reason": decision["reason"]}))
        return
    delim = f"FUZE_REVIEW_BODY_{_secrets_mod.token_hex(8)}"
    with open(out_path, "a", encoding="utf-8") as fh:
        fh.write(f"decision={decision['decision']}\n")
        fh.write(f"body<<{delim}\n{body}\n{delim}\n")


def main() -> int:
    action_conclusion = os.environ.get("FUZE_ACTION_CONCLUSION", "")
    result_text = os.environ.get("FUZE_RESULT_TEXT", "")
    nonce = os.environ.get("FUZE_VERDICT_NONCE", "")
    mode = os.environ.get("FUZE_ACTION_MODE", "")
    vendor = os.environ.get("FUZE_ACTION_VENDOR", "")
    sensitive_raw = os.environ.get("FUZE_SENSITIVE_FILES", "")
    sensitive_files = [line for line in sensitive_raw.splitlines() if line.strip()]

    result = decide(action_conclusion, result_text, nonce, sensitive_files, mode)
    body = render_body(result, mode, vendor)

    print(f"::notice title=fuze-code-review::decision={result['decision']} reason={result['reason']}")
    _write_github_output(result, body)

    return 0


if __name__ == "__main__":
    sys.exit(main())
