---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fuzefront-registration
  namespace: fuzex
spec:
  encryptedData:
    token: AgCqquHde0C4Tcka1GMQuQ3hJNgZTC2pRVFv7Deu7Ih4hfcafJCMjK0eI7ebqXioiztOYtbAvsx6u+OpuQr65OwI88wxpi6QD8x8lFJ7vzwgPSZm25Xnp64IP4TgRncaASRzxZJQDwnMqb2jdxvZ+uhfNRXcCIEBObEWrhQjhvIuRn4bx/QcFgOw4bq3B+HZgPZ7DGMckPbt+4QiTyRkWCNgA3Jd2nQQ9w4wBSuqXe9NJBo6u0jMEpMPNuBdGdf3WWjx3ecJSuvBUTKkx5DSoNvqtFx2/+/mYnutg3bLpjljxO2vzePNQt2C5sd28aTMv5GcymOjK4MqhLaGRO2INH4OuOnKtxJyQhrhqw5Tr231zaC/uvAq/ZVjb0k/wkpJ5MsQ4WeftEY1xL0yELQ375nOpn/RR9IyaoVokBl2jfpC99Xc1jvn+ELgcRIoWv2yubnepafe7xJyGwPlENuH4mnC9QU6W9pGcEYO1ujxZLqq20ktjg9PD/W9bqPEWa5IU17M4h2nXbPhSAdrwZCfYJuaN9CRY6DShjpvEFrBRfuFo/en+7cb1qdC/1ONCwI+9PN874At2lDvtDMN3oCNxPDJzSSh4ot5NbcBvbY9BUf86bUqFF1jvUq7h9MAgY9IjzHTj+LpQ7+9cRUtCXw519/fcy8ovo+9JYJ4Cqg6xWzQbH0QOMYfLXVa1HRoI2JiRFiTn1FA9V8CSnbXkAA3xR6giox4zQ8DkB+o1jxdwOYTAuyIu4LSRpn72C55o+uOuK/vYVXGABFrjHcwLisWQHPF
  template:
    metadata:
      creationTimestamp: null
      name: fuzefront-registration
      namespace: fuzex
    type: Opaque
